version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Admin123!
      MYSQL_DATABASE: gym-management-systemdb
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: gymbuddy-app
    ports:
      - "8080:8080"  # Spring Boot app
      - "5005:5005"  # Remote debugger
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/gym-management-systemdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Admin123!
    #restart: on-failure

volumes:
  mysql-data: