spring:
  profiles:
    active: ${profileActive:dev}

---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: jdbc:h2:mem:localDB
    username: devUser
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true  # Enable H2 web console
      path: /h2-console  # The URL path to access the console