spring:
  profiles:
    active: ${profileActive:dev}

---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: jdbc:mysql://localhost:3306/gym-management-systemdb
    username: root
    password: Admin123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Automatically updates schema on startup
    show-sql: true      # Optional: Shows SQL queries in the console
    properties:
      hibernate:
        format_sql: true  # Formats SQL for better readability
  logging:
    level:
      org.hibernate.SQL: DEBUG # Enables SQL logs for debugging